apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: auto-label-namespaces
spec:
  rules:
    - name: add-custom-label
      match:
        resources:
          kinds: ["Namespace"]
      preconditions:
        all:
          - key: "{{request.operation}}"
            operator: Equals
            value: "CREATE"
      mutate:
        patchStrategicMerge:
          metadata:
            labels:
              pod-security.kubernetes.io/enforce: privileged
